name: CD

on:
  release:
    types:
      - published

jobs:
  cd:
    uses: halo-sigs/reusable-workflows/.github/workflows/plugin-cd.yaml@v3
    secrets:
      halo-pat: ${{ secrets.HALO_PAT }}
    permissions:
      contents: write
    with:
      app-id: app-KhIVw
      node-version: "20"
      pnpm-version: "9"
      ui-path: "ui"
      artifacts-path: 'app/build/libs'
